# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyer_items', '0002_auto_20170108_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flyeritem',
            old_name='extra_text',
            new_name='price_prefix',
        ),
        migrations.RenameField(
            model_name='flyeritem',
            old_name='price_text',
            new_name='price_suffix',
        ),
        migrations.AddField(
            model_name='flyeritem',
            name='sale_text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
