# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyer_items', '0003_auto_20170108_2117'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='flyeritem',
            unique_together=set([('external_id', 'flyer_id')]),
        ),
    ]
