# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-08 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyer_items', '0004_auto_20170108_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyeritem',
            name='disclaimer_text',
            field=models.CharField(default='', max_length=255),
        ),
    ]
