# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyer_items', '0005_flyeritem_disclaimer_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyeritem',
            name='disclaimer_text',
            field=models.TextField(default=''),
        ),
    ]
