# Generated by Django 2.1.3 on 2018-11-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyer_items', '0006_auto_20170129_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyeritem',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
