# Generated by Django 2.1.3 on 2018-11-04 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyer_items', '0007_auto_20181104_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyeritem',
            name='image_url',
            field=models.CharField(default='', max_length=255),
        ),
    ]
